/*
 * local_events_device.h
 *
 *  Created on: Oct 23, 2023
 *      Author: t126401
 */

#ifndef COMPONENTS_INTERFAZ_USUARIO_INCLUDE_LOCAL_EVENTS_DEVICE_H_
#define COMPONENTS_INTERFAZ_USUARIO_INCLUDE_LOCAL_EVENTS_DEVICE_H_




typedef enum EVENT_DEVICE {

	EVENT_NONE,
	EVENT_UP_THRESHOLD,
	EVENT_DOWN_THRESHOLD,
	EVENT_RESET_BUTTON,
	EVENT_ACTION_BUTTON,
	EVENT_RELAY_ON,
	EVENT_RELAY_OFF,
	EVENT_REQUEST_TEMPERATURE,
	EVENT_WAITING_RESPONSE_TEMPERATURE,
	EVENT_ANSWER_TEMPERATURE,
	EVENT_TIMEOUT_REMOTE_TEMPERATURE,
	EVENT_ERROR_READ_LOCAL_TEMPERATURE


}EVENT_DEVICE;


typedef enum SUB_STATUS_APP {

	NORMAL_SUB_STATUS,
	SUN_SUB_STATUS,
	MOON_SUB_STATUS
} SUB_STATUS_APP;




#endif /* COMPONENTS_INTERFAZ_USUARIO_INCLUDE_LOCAL_EVENTS_DEVICE_H_ */
