/*
 * local_events_device.h
 *
 *  Created on: Oct 23, 2023
 *      Author: t126401
 */

#ifndef COMPONENTS_INTERFAZ_USUARIO_INCLUDE_LOCAL_EVENTS_DEVICE_H_
#define COMPONENTS_INTERFAZ_USUARIO_INCLUDE_LOCAL_EVENTS_DEVICE_H_




typedef enum EVENT_DEVICE {

	EVENT_NONE,
	EVENT_SHORT_PUSH_BUTTON,
	EVENT_LARGE_PUSH_BUTTON,
	EVENT_VERY_LARGE_PUSH_BUTTON,
	EVENT_OP_LOCAL_RELAY,
	EVENT_OP_REMOTE_RELAY



}EVENT_DEVICE;


char* local_event_2_mnemonic(EVENT_DEVICE event);




#endif /* COMPONENTS_INTERFAZ_USUARIO_INCLUDE_LOCAL_EVENTS_DEVICE_H_ */
